# Generated by Django 3.0.5 on 2020-04-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
    ]
