# Generated by Django 3.0.5 on 2020-04-10 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200409_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date',
        ),
        migrations.AddField(
            model_name='books',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
