# Generated by Django 3.0.5 on 2020-04-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200410_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
            ],
        ),
    ]
