# Generated by Django 3.0.5 on 2020-04-10 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария'),
        ),
    ]
