# Generated by Django 3.0.5 on 2020-04-29 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20200429_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='books_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
