# Generated by Django 3.0.5 on 2020-04-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comments_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
