# Generated by Django 3.0.5 on 2020-04-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200411_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='books.Books'),
        ),
    ]
