# Generated by Django 3.0.5 on 2020-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_comments_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
