# Generated by Django 3.0.5 on 2020-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200423_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
