# Generated by Django 3.0.5 on 2020-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_comments_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_title',
            field=models.CharField(max_length=80),
        ),
    ]
