# Generated by Django 3.0.5 on 2020-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200425_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.TextField(default=100),
        ),
    ]
