# Generated by Django 3.0.5 on 2020-04-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20200428_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.JPG', upload_to='media/avatar'),
        ),
    ]
